[package]
name = "main"
version = "0.1.0"
authors = ["PeerHenry <peerhenry@gmail.com>"]

[dependencies]
libc = "*"
cgmath = "0.15.0"
gl = "*"
glutin = "0.9.2"
image = "*"
uniforms = { git = "https://github.com/peerhenry/solid_uniforms" }